# Generated by Django 3.0.1 on 2020-07-12 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250)),
                ('email', models.CharField(default='', max_length=250)),
                ('phonenum', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250)),
                ('email', models.CharField(default='', max_length=250)),
                ('phonenum', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School_register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=154)),
                ('country', models.CharField(max_length=150)),
                ('contact', models.IntegerField()),
                ('school_name', models.CharField(max_length=150)),
                ('school_address', models.CharField(max_length=250)),
                ('school_city', models.CharField(max_length=150)),
                ('school_pincode', models.CharField(max_length=50)),
                ('school_website', models.CharField(max_length=250)),
                ('school_email', models.EmailField(max_length=254)),
                ('pname', models.CharField(max_length=150)),
                ('pmobile', models.IntegerField()),
                ('exammode', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='cyberolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='englisholym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='internationalspell',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mathsolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reasoningolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='scienceolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='street',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='abc', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mathsolym', models.BooleanField(default=False, null=True)),
                ('scienceolym', models.BooleanField(default=False, null=True)),
                ('englisholym', models.BooleanField(default=False, null=True)),
                ('reasoningolym', models.BooleanField(default=False, null=True)),
                ('cyberolym', models.BooleanField(default=False, null=True)),
                ('internationalspell', models.BooleanField(default=False, null=True)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
