# Generated by Django 3.0.1 on 2020-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200712_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=250)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('correct', models.CharField(max_length=150)),
            ],
        ),
    ]
