# Generated by Django 3.0.1 on 2020-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='answer',
        ),
        migrations.AddField(
            model_name='paper',
            name='option_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='option_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='option_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='option_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
