# Generated by Django 3.0.3 on 2020-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200719_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='final_cyberolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='final_englisholym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='final_internationalspell',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='final_mathsolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='final_reasoningolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='final_scienceolym',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
