# Generated by Django 3.0.3 on 2020-07-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200723_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='final_cyberolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='final_englisholym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='final_internationalspell',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='final_mathsolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='final_reasoningolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='final_scienceolym',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
