# Generated by Django 3.0.3 on 2020-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200723_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='order_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
