# Generated by Django 3.0.1 on 2020-07-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_student_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to='photograph/'),
        ),
        migrations.AddField(
            model_name='student',
            name='prev_marksheet',
            field=models.ImageField(max_length=255, null=True, upload_to='previous_marksheet/'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.ImageField(max_length=255, null=True, upload_to='school_id/'),
        ),
    ]
