# Generated by Django 3.0.3 on 2020-07-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_student_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='idproof',
            field=models.ImageField(blank=True, upload_to='idproof'),
        ),
        migrations.AddField(
            model_name='student',
            name='marksheet',
            field=models.ImageField(blank=True, upload_to='marksheet'),
        ),
        migrations.AddField(
            model_name='student',
            name='photograph',
            field=models.ImageField(blank=True, upload_to='photograph'),
        ),
    ]
