# Generated by Django 3.0.3 on 2020-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200728_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idproof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proof/%Y/%m/%d', verbose_name='Figure1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='mark_sheet/%Y/%m/%d', verbose_name='Figure2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d', verbose_name='Figure3'),
        ),
    ]
