# Generated by Django 3.0.1 on 2020-07-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200727_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img1',
            field=models.ImageField(null=True, upload_to='option/'),
        ),
        migrations.AddField(
            model_name='question',
            name='img2',
            field=models.ImageField(null=True, upload_to='option/'),
        ),
        migrations.AddField(
            model_name='question',
            name='img3',
            field=models.ImageField(null=True, upload_to='option/'),
        ),
        migrations.AddField(
            model_name='question',
            name='img4',
            field=models.ImageField(null=True, upload_to='option/'),
        ),
    ]
