# Generated by Django 3.0.3 on 2020-07-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200729_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idproof',
            field=models.ImageField(blank=True, null=True, upload_to='idproof'),
        ),
        migrations.AlterField(
            model_name='student',
            name='marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='marksheet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
