# Generated by Django 3.0.1 on 2020-07-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200729_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img1',
            field=models.ImageField(null=True, upload_to='option/', verbose_name='Image1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='img2',
            field=models.ImageField(null=True, upload_to='option/', verbose_name='Image2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='img3',
            field=models.ImageField(null=True, upload_to='option/', verbose_name='Image3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='img4',
            field=models.ImageField(null=True, upload_to='option/', verbose_name='Image4'),
        ),
    ]
