# Generated by Django 3.0.3 on 2020-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200729_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img1',
            field=models.ImageField(null=True, upload_to='option1/', verbose_name='Image1'),
        ),
        migrations.AddField(
            model_name='question',
            name='img2',
            field=models.ImageField(null=True, upload_to='option2/', verbose_name='Image2'),
        ),
        migrations.AddField(
            model_name='question',
            name='img3',
            field=models.ImageField(null=True, upload_to='option3/', verbose_name='Image3'),
        ),
        migrations.AddField(
            model_name='question',
            name='img4',
            field=models.ImageField(null=True, upload_to='option4/', verbose_name='Image4'),
        ),
    ]
