# Generated by Django 3.0.1 on 2020-07-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20200729_1515'),
        ('quiz', '0010_auto_20200729_1359'),
    ]

    operations = [
    ]
