# Generated by Django 3.0.3 on 2020-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20200729_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ispaid',
            field=models.BooleanField(blank=True, default=False, help_text='If yes, than  quiz is subscribed by user'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='ispaid_final',
            field=models.BooleanField(blank=True, default=False, help_text='If yes, than  quiz is subscribed by user'),
        ),
    ]
