# Generated by Django 3.0.3 on 2020-08-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20200801_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='internationalspell',
        ),
        migrations.AddField(
            model_name='student',
            name='cyberquiz',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='englishquiz',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gkquiz',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mathquiz',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reasoningquiz',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sciencequiz',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
    ]
