# Generated by Django 3.0.3 on 2020-08-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20200801_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='final_internationalspell',
        ),
    ]
