# Generated by Django 3.0.3 on 2020-08-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_remove_student_final_internationalspell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='final_internationalspell',
            new_name='final_generalolym',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='internationalspell',
            new_name='generalolym',
        ),
        migrations.AddField(
            model_name='student',
            name='cybertime',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='englishtime',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gktime',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mathtime',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='quiz_to_change',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reasoningtime',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sciencetime',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
    ]
