# Generated by Django 3.0.1 on 2020-08-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20200802_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='idproof_date',
            field=models.CharField(default='Not Submitted yet', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='marksheet_date',
            field=models.CharField(default='Not Submitted yet', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='photograph_date',
            field=models.CharField(default='Not Submitted yet', max_length=50),
        ),
    ]
