# Generated by Django 3.0.1 on 2020-08-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20200802_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idproof_date',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='marksheet_date',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='photograph_date',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
