# Generated by Django 3.0.1 on 2020-08-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20200804_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idproof_date',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
