# Generated by Django 3.0.1 on 2020-08-04 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20200804_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=50)),
                ('order_amount', models.CharField(max_length=50)),
                ('reference_id', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(max_length=50)),
                ('pay_time', models.CharField(max_length=50)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
