# Generated by Django 3.0.1 on 2020-08-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_invoice_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
    ]
