# Generated by Django 3.0.6 on 2020-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20200804_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('olympiad_name', models.CharField(max_length=20)),
                ('std', models.CharField(max_length=2)),
                ('syllabus', models.CharField(max_length=1000)),
            ],
        ),
    ]
