# Generated by Django 3.0.3 on 2020-08-10 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Standard')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Standard', verbose_name='Standard'),
        ),
    ]
