# Generated by Django 3.0.3 on 2020-08-10 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20200810_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Standard', verbose_name='Standard'),
        ),
    ]
