# Generated by Django 3.0.3 on 2020-08-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_quiz_standard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='fail_text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='success_text',
        ),
    ]
