# Generated by Django 3.0.3 on 2020-08-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20200813_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
    ]
