# Generated by Django 3.0.1 on 2021-03-13 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_auto_20200821_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=500)),
                ('suggestion', models.CharField(max_length=500)),
                ('review', models.CharField(max_length=500)),
                ('feedbackBy', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
    ]
