# Generated by Django 3.0.1 on 2021-03-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='street',
            new_name='city',
        ),
    ]
