# Generated by Django 3.0.1 on 2021-03-23 01:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_auto_20210323_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_country',
            field=django_countries.fields.CountryField(default='Afganistan', max_length=2),
        ),
    ]
