# Generated by Django 3.0.1 on 2021-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_auto_20210328_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='phonenum',
            field=models.CharField(max_length=15),
        ),
    ]
