# Generated by Django 3.0.1 on 2021-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_auto_20210405_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cybertime_finalexam',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='englishtime_finalexam',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gktime_finalexam',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mathtime_finalexam',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reasoningtime_finalexam',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sciencetime_finalexam',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
    ]
