# Generated by Django 3.0.1 on 2021-04-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_auto_20210405_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quiz_to_change_finalexam',
            field=models.CharField(default='nil', max_length=100, null=True),
        ),
    ]
