# Generated by Django 3.0.1 on 2021-04-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_student_quiz_to_change_finalexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenum',
            field=models.CharField(max_length=15),
        ),
    ]
